# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xft.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\txft.proto\"C\n\x0fGenerateRequest\x12\x0b\n\x03Ids\x18\x01 \x03(\x05\x12\x12\n\nbatch_size\x18\x02 \x01(\x05\x12\x0f\n\x07seq_len\x18\x03 \x01(\x05\"D\n\x10GenerateResponse\x12\x0b\n\x03Ids\x18\x01 \x03(\x05\x12\x12\n\nbatch_size\x18\x02 \x01(\x05\x12\x0f\n\x07seq_len\x18\x03 \x01(\x05\"*\n\x12StopServiceRequest\x12\x14\n\x0cstop_service\x18\x01 \x01(\x08\"&\n\x13StopServiceResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xb6\x01\n\nXFTService\x12\x30\n\x07predict\x12\x10.GenerateRequest\x1a\x11.GenerateResponse\"\x00\x12\x39\n\x0epredict_stream\x12\x10.GenerateRequest\x1a\x11.GenerateResponse\"\x00\x30\x01\x12;\n\x0cstop_service\x12\x13.StopServiceRequest\x1a\x14.StopServiceResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GENERATEREQUEST']._serialized_start=13
  _globals['_GENERATEREQUEST']._serialized_end=80
  _globals['_GENERATERESPONSE']._serialized_start=82
  _globals['_GENERATERESPONSE']._serialized_end=150
  _globals['_STOPSERVICEREQUEST']._serialized_start=152
  _globals['_STOPSERVICEREQUEST']._serialized_end=194
  _globals['_STOPSERVICERESPONSE']._serialized_start=196
  _globals['_STOPSERVICERESPONSE']._serialized_end=234
  _globals['_XFTSERVICE']._serialized_start=237
  _globals['_XFTSERVICE']._serialized_end=419
# @@protoc_insertion_point(module_scope)
